(list
 '((#:name . "ipdb-packages")
   (#:load-path-inputs . ("guix" "conf"))
   (#:package-path-inputs . ("conf"))
   (#:proc-input . "conf")
   (#:proc-file . "ci/jobs.scm")
   (#:proc . cuirass-jobs)
   (#:proc-args . ((((#:package-name . bigchaindb)
                     (#:system . "x86_64-linux"))
                    ((#:package-name . tendermint-bin)
                     (#:system . "x86_64-linux")))))
   (#:inputs . (((#:name . "guix")
                 (#:url . "git://git.savannah.gnu.org/guix.git")
                 (#:load-path . ".")
                 (#:branch . "master")
                 (#:no-compile? . #t))
                ((#:name . "conf")
                 (#:url . "git://github.com/ipdb/ipdb-guix.git")
                 (#:load-path . ".")
                 (#:branch . "master")
                 (#:no-compile? . #t))))))
